57 create pet form
BC-MAY-21-RN/proyecto-final-m22-pf-t1-reactive-01 pull request #58
Opened 2022-08-06 22:11 UTC by FranciscoSenestrari

# Description
What did you implemented/Why did you implemented this:
 -Need create view to pet input information
  ## Screenshots 
If applicable, include screenshots of the results or screenshots that help to see changes
![Screenshot_1659808871](https://user-images.githubusercontent.com/17836921/183267539-39bec619-ee06-4018-8ceb-3e15964c0595.png)

2022-08-08 18:03 UTC, YilKanda requested changes

2022-08-08 18:03 UTC, YilKanda commented on src/components/InputPetInfo/Input.js
> +});
Place the styles in an external file.

2022-08-09 03:56 UTC, FranciscoSenestrari commented on src/components/InputPetInfo/Input.js
> +});
changes required complete

2022-08-09 18:05 UTC, YilKanda approved these changes
LGTM!

2022-08-09 20:06 UTC, ayeza-zamudio3 approved these changes

2022-08-09 20:24 UTC, nicolasjrz approved these changes

2022-08-09 20:29 UTC, merged